spring.application.name=SchoolManagement
server.port=8080

#main database
spring.datasource.url=jdbc:mysql://localhost:3306/school_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

#Vector store database
spring.ai.vectorstore.pgvector.datasource.url=jdbc:mysql://localhost:3306/school_db
spring.ai.vectorstore.pgvector.datasource.username=root
spring.ai.vectorstore.pgvector.datasource.password=root
spring.ai.vectorstore.pgvector.initialize-schema=true


