ALTER TABLE IF EXISTS fee_payments ALTER COLUMN fee_structure_id DROP NOT NULL;
ALTER TABLE IF EXISTS fee_payments ALTER COLUMN student_id DROP NOT NULL;
ALTER TABLE IF EXISTS exams ALTER COLUMN exam_type_id DROP NOT NULL;
ALTER TABLE IF EXISTS exams ALTER COLUMN branch_id DROP NOT NULL;
